baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Yassine portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

pagination:
  pagerSize: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

# Menus:
#   main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    # - identifier: gallery
    #   name: Gallery
    #   title: Blog posts
    #   url: /gallery
    #   weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Yassine Portfolio"
  description: Yassine Safraoui Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/fav.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Yassine Safraoui" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable: true
      showOnScrollUp: true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Yassine Safraoui."
    subtitle: "I'm a [SEOC](https://phelma.grenoble-inp.fr/fr/formation/ingenieur-de-grenoble-inp-phelma-filiere-systemes-embarques-et-objets-connectes-seoc) engineering student @Phelma."
    content: "Passionate about embedded systems and connected objects. I'm looking for a 6 months internship in this domain"
    image: /fav.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/Yassine_SAFRAOUI_CV.pdf"
      download: true
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/yassine-safraoui
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/yassine-safraoui-226993200

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/me.png"
    content: |-
      I am an engineering student specialized in Embedded Systems and Connected Objects @Phelma - Grenoble INP. I have a background in computer science and digital electronics. I am currently looking for a 6 months last year internship,

    skills:
      enable: true
      title: "here are the domains I'm interested in:"
      items:
        - "Realtime Linux programming: FreeRTOS"
        - C/C++ Development
        - Control systems
        - "HLS Design: VHDL"

  # Experience
  experience:
    enable: true
    title: "Experiences"
    items:
      - job: "Software Developer"
        company: "Laboratoire d'Informatique de Grenoble LIG"
        companyUrl: "https://www.liglab.fr/fr"
        date: "May 2024 - August 2024"
        info:
          enable: true
          content: 10 Weeks Internship
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |-
          Investigating migration from the existing [Moodle REST API](https://docs.moodle.org/dev/Web_service_API_functions) to a Hasura GraphQL API to eliminate over-fetching and under-fetching of data.
      - job: "Software Developer Intern"
        company: "VITsolutions"
        companyUrl: "https://www.vitsolutions.eu/"
        date: "July 2023 - August 2023"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: |-
          - Built a Sharepoint React Gantt chart webpart for a Sharepoint site.
          - Developed POWERAPP Application for a client.

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: true
    items:
      - title: "Engineering school - SEOC specialization"
        school:
          name: "PHELMA - Grenoble INP"
          url: "https://phelma.grenoble-inp.fr/"
        date: "2022 - 2025"
        content: Engineering school in Physics, Electronics and Materials.
      - title: "Preparatory classes"
        school:
          name: "Lycée Mohammed VI d'excellence - Ben Guerir"
          url: "https://www.firsi.org/soutien-a-l-enseignement-d-excellence/lycee-mohammed-vi-d-excellence"
        date: "2020 - 2022"
        content: Intensive undergraduate studies Technical Sciences and Technologies specialization(TSI). Includes a strong foundation in mathematics, electronics and control systems.
      - title: "Baccalauréat STE"
        school:
          name: "Lycée Les Orangers - Rabat"
        date: "2017 - 2020"
        content: Scientific baccalaureate with high honors.

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Control Software for NXP CUP CAR
        content: Worked in a team of 2 to build C-based Realtime Control Software for the NXP CUP CAR using FreeRTOS. We used interrupts to handle sensors input (wheel encoders + 2D camera) and implemented feedback loop control algorithms to control wheel's speed and direction with FreeRTOS scheduled tasks.
        badges:
          - name: "School project"
            color: "text-bg-primary"
          - name: "C"
          - name: "Realtime programming"
          - name: "FreeRTOS"
          - name: "Interrupts"
          - name: "Control systems"
      - title: Developed a compiler for the DECA language in Java
        content: Worked in a team of 5 mixed Phelma and Ensimag students to build a compiler for the DECA language. We also developed an extension of the language to facilitate the development of Gameboy games.
        badges:
          - name: "School project"
            color: "text-bg-primary"
          - name: "Java"
          - name: "ANTLR"
          - name: "JUnit 4"
          - name: "Mockito"
          - name: "Gameboy assembly"
      - title: C Spell Checker
        content: "Wroked in a team of 4 on implementating and benchmarking various spellchecking algorithms and data structures with C.\ne.g: resizable arrays, linked lists, hash sets, trees, Tries. DFS, BFS."
        badges:
          - name: "School project"
            color: "text-bg-primary"
          - name: "C"
          - name: "Makefile"
          - name: "Algorithms"
          - name: "Data structures"
      - title: Pathfinding algorithms in C
        content: "Wroked in a team of 3 on implementating different Pathfinding algorithms(DFS, BFS and Dijkstra) in C and benchmarking them on a map of train stations."
        badges:
          - name: "School project"
            color: "text-bg-primary"
          - name: "C"
          - name: "Makefile"
          - name: "DFS"
          - name: "BFS"
          - name: "Dijkstra"
      - title: Simulating a Multi-agent system in Java
        content: Simulated multi-agent systems in Java Cellular Automata and Boids with predator-prey behavior, showcasing object-oriented design and event-driven programming.
        badges:
          - name: "School project"
            color: "text-bg-primary"
          - name: "Java"
          - name: "OOP"
          - name: "Event-driven programming"
      - title: VHDL Design of a Digital Filter
        content: Worked in a team of 2 on the Implementation of the Design of an FSM-based VHDL Filter. We used ModelSim to simulate the design during development, SpyGlass to validate the synthesizability of the design, Precision RTL to synthetise the design and Xilinx ISE for routing and placement and tested the design on a FPGA Xilinx Spartan3 board.
        badges:
          - name: "School project"
            color: "text-bg-primary"
          - name: "VHDL"
          - name: "ModelSim"
          - name: "SpyGlass"
          - name: "Precision RTL"
          - name: "Xilinx ISE"
      - title: C Messaging Client
        content: "Wroked in a team of 2 on implementating a messaging client for an existing server in C using System V IPC mechanisms."
        badges:
          - name: "School project"
            color: "text-bg-primary"
          - name: "C"
          - name: "CMake"
          - name: "System V IPC"
          - name: "Multithreading"
          - name: "Multiprocessing"
          - name: "Mutex"
          - name: "Semaphore"
          - name: "Multiprocessing"
          - name: "Mutex"
          - name: "Semaphore"
      - title: Chamilo Sync Kotling Android App
        content: Developed a Kotlin Android app to synchronize contents of courses from Chamilo with Local storage. Used Dagger Hilt for dependency injection, OKHttp for network requests, Room and Coroutines for asynchronous programming.
        badges:
          - name: "Kotlin"
          - name: "Jetpack Compose"
          - name: "Dagger Hilt"
          - name: "Room Database"
      - title: Advent of Code 2024
        content: Participated in the Advent of Code 2024 and learned the Rust programming language.
        badges:
          - name: "Rust"
          - name: "Algorithms"
          - name: "Data structures"
        links:
          - icon: fab fa-github
            url: https://github.com/yassine-safraoui/advent-of-code-2024
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        badges:
          - name: "Hugo"
          - name: "Bootstrap"
          - name: "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile # TODO: Change this to your repository
      - title: Kotlin Springboot API typesafe React frontend
        content: Showcased how to use a Kotlin/Java Springboot backend with a React frontend while ensuring typesafe API calls using OpenAPI.
        badges:
          - name: "Kotlin"
          - name: "Springboot"
          - name: "Orval"
          - name: "React"
          - name: "Typescript"
          - name: "TailwindCSS"
          - name: "TanStack Query"
        links:
          - icon: fab fa-github
            url: https://github.com/yassine-safraoui/spring-boot-react-openapi

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:yassine.safraoui@phelma.grenoble-inp.fr
    formspree:
      enable: true # `contact.email` value will be ignored
      formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "Enter your email address"
      messageCaption: "Enter your message here"
      messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/yassine-safraoui
      linkedin: https://www.linkedin.com/in/yassine-safraoui-226993200/

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
